// module version: 0.1.0  (independent of the app version in CMakeLists project(VERSION))

/**
 * @file vulkan/pass/gbuffer_debug.cppm
 * @brief The fifteenth real pass: the G-buffer debug view, which shows the stored surface one channel at a time.
 * @defgroup vulkan_pass_gbuffer_debug G-buffer Debug View Pass
 *
 * WHY IT IS A PASS AND WHAT IT OWNS: the view is a fullscreen triangle over the HDR target, so it owns its set
 * layout (the G-BUFFER family's, nine-plus bindings generated by `pipelines::build_gbuffer_debug`), its pipeline
 * layout, its pipeline and its recording - the four images it moves to a sampled layout, the CLEAR instance, the
 * one-set bind, the 16-byte push and the draw. IT IS ALSO THE PASS THAT OWNS THE G-BUFFER SET LAYOUT, which the
 * deferred lighting stage asks for by index: one layout, built here because `build_gbuffer_debug` is what creates
 * it, and reached by the other pass through `pass_context::shared_set_layout(1)`.
 *
 * WHAT IT DOES NOT OWN, and each is a shared thing rather than an omission: the per-image SETS
 * (`bindings::image_set_family`), which SIX consumers bind and the renderer therefore writes
 * (`ensure_gbuffer_descriptors`); the two samplers, which a declaration picks by hint and the renderer creates;
 * and two pieces of per-image bookkeeping the frame carries as a callback - the G-buffer depth's transition (its
 * old layout depends on whether the G-buffer instance rendered this frame) and clearing the flag that says the
 * motion-vector target has been handed to a sampler (which this pass does, because it runs INSTEAD of the
 * lighting stage and is the only stage that samples that image on those frames).
 *
 * THE HDR TARGET'S TRANSITION IS THE FRAME LOOP'S, for the same reason the post chain's is: it has to happen even
 * on the frame the descriptor set is missing, because the post chain samples that image - and it is the frame loop
 * that owns the fallback (a cleared instance, which is what makes such a frame black rather than undefined).
 */

module;

#include <array>
#include <cstdint>
#include <cstring>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vulkan/vulkan.h>

export module vulkan.pass.gbuffer_debug;

import vulkan.pass;
import vulkan.render_resource;
import vulkan.core.handles; // vk_pipeline: the RAII owner of the pipeline this pass builds

export namespace vulkan::pass {

    /// @brief what the renderer hands the view: the two per-image pieces of bookkeeping it cannot own
    struct gbuffer_debug_frame {
        /**
         * The renderer's two shared per-image transitions: the G-buffer depth's hand-back (whose "was it written
         * this frame" flag belongs to the pass that wrote it) and the motion-vector flag's clearing (which stops
         * the GI chain from transitioning that image a second time in the same frame). Both are the same shape as
         * the deferred lighting stage's `ensure_inputs`, and for the same reason.
         */
        void (*ensure_inputs)(void* owner, VkCommandBuffer command_buffer, uint32_t image_index) = nullptr;
        void* owner = nullptr;
    };

    /**
     * @brief the G-buffer debug view: one stored channel, displayed in the HDR target
     *
     * It runs INSTEAD of the deferred lighting stage (the two write the HDR target in incompatible ways), which is
     * what makes it the frame's only sampler of the motion-vector target and what keeps it off the TAA path.
     */
    class gbuffer_debug_pass final : public frame_pass {
    public:
        /// @brief the push block, which is also `gbuffer_debug.frag`'s
        struct push_constants {
            float channel = 1.0f; // 0 albedo, 1 normal, 2 roughness, 3 metallic, 4 ao, 5 id, 6 depth, 7 flags, 8 motion
            float proj_22 = 0.0f; // projection[2][2] / [3][2]: the depth-linearization terms
            float proj_32 = 0.0f;
            // Amplification for the motion channel only. The stored vector is a UV-space delta, so a pixel of motion
            // at 1080 wide is 0.00093 and the raw value would be black everywhere; the renderer sets this to
            // width/4 so four pixels saturate the channel, which scales itself across resolutions instead of being
            // a magic number per window size.
            float motion_gain = 1.0f;
        };

        gbuffer_debug_pass() = default;
        ~gbuffer_debug_pass() override;

        [[nodiscard]] render_resource::pass_io const& io() const noexcept override;
        [[nodiscard]] vulkan::pass::behaviour const& behaviour() const noexcept override;
        [[nodiscard]] std::string_view feature() const noexcept override;
        void create(pass_context const& context) override;
        void on_swapchain_recreated(pass_host const& host) override;
        void record(resolved_io const& io) override;

        /// @brief whether the pass built everything it records with (the renderer gates the feature on this)
        [[nodiscard]] bool pipeline_ready() const noexcept;
        /// @brief the pipeline the runner binds before this pass records
        [[nodiscard]] VkPipeline pipeline() const noexcept;
        /// @brief the layout that pipeline binds its set and takes its push block through
        [[nodiscard]] VkPipelineLayout pipeline_layout() const noexcept;
        /// @brief the G-BUFFER SET LAYOUT, which the deferred lighting stage also binds (it asks the context for
        ///        index 1): one layout, built here, because this is the pass whose builder creates it
        [[nodiscard]] VkDescriptorSetLayout set_layout() const noexcept;

        void set_frame(gbuffer_debug_frame const& frame) noexcept;

    private:
        static constexpr std::string_view vertex_shader_name = "post.vert.spv"; // the synthetic fullscreen triangle
        static constexpr std::string_view fragment_shader_name = "gbuffer_debug.frag.spv";

        static constexpr std::array<std::string_view, 1> pipeline_names = {"gbuffer-debug"};
        inline static constexpr vulkan::pass::behaviour behaviour_ = {
            .kind = behaviour_kind::fullscreen,
            .extent = extent_rule::full, // the view runs at the frame's resolution
            .extent_of = resource_id::none,
            .pipelines = pipeline_names,
            .resync_viewport = true, // the runner sets the viewport and scissor from io.extent
        };
        void release_owned() noexcept;

        VkDevice device_ = VK_NULL_HANDLE;
        VkDescriptorSetLayout set_layout_ = VK_NULL_HANDLE;
        VkPipelineLayout pipeline_layout_ = VK_NULL_HANDLE;
        std::optional<vk_pipeline> pipeline_ = std::nullopt;
        gbuffer_debug_frame frame_ = {};
    };

    static_assert(sizeof(gbuffer_debug_pass::push_constants) == render_resource::gbuffer_debug_io.push->size,
                  "the debug view's declared push block must be the size of the struct the renderer composes");

} // namespace vulkan::pass
